const ATTRIBUTE_PREFIX = "data-color-analyzer";
const ATTRIBUTE_ID = `${ATTRIBUTE_PREFIX}-id`;
const ORIGINAL_BACKGROUND_COLOR_ATTRIBUTE = `${ATTRIBUTE_PREFIX}-original-inline-background-color`;
const ORIGINAL_COLOR_ATTRIBUTE = `${ATTRIBUTE_PREFIX}-original-inline-color`;
const GROUP_ATTRIBUTE = `${ATTRIBUTE_PREFIX}-group`;

const SKIP_NODE_NAMES = ["SCRIPT", "IFRAME", "NOSCRIPT", "STYLE"];

export {
  SKIP_NODE_NAMES,
  ATTRIBUTE_PREFIX,
  ATTRIBUTE_ID,
  ORIGINAL_BACKGROUND_COLOR_ATTRIBUTE,
  ORIGINAL_COLOR_ATTRIBUTE,
  GROUP_ATTRIBUTE,
};
